# -*- coding: utf-8 -*-
"""L1_Congestion_Balanced_HighAccuracy_EXECUTED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqLHYi-pf6KTIuY6fONy2uwLylvw0mrv

# L1 Container Congestion Predictor — Balanced High-Accuracy Congestion Test

This notebook is designed so the **test set is completely untouched** until final evaluation.

### Objective
Predict **Congestion Risk** before scheduled arrival.

### Target
`Congestion Risk = 1` when actual arrival (`ATA`) is more than 30 minutes after scheduled arrival (`etaSchedule`).

### Model
- XGBoost
- LightGBM
- 50/50 probability ensemble

### Important evaluation rule
The threshold is selected **only from the validation set**. The final test set is then evaluated once. No test labels are used for training, threshold selection, class-weight selection, or feature engineering.
"""

# 1. Imports
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # non-interactive backend for script execution
import matplotlib.pyplot as plt
import joblib

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    fbeta_score, balanced_accuracy_score, roc_auc_score,
    classification_report, confusion_matrix, ConfusionMatrixDisplay
)

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

RANDOM_STATE = 42
CONGESTION_THRESHOLD_MIN = 30

print("All imports successful.")

# 2. Load CSV safely
candidates = [
    Path("tracking_db(3).csv"),
    Path("tracking_db.csv"),
    Path("/mnt/data/tracking_db(3).csv"),
    Path("/mnt/data/tracking_db.csv"),
]

DATA_PATH = next((p for p in candidates if p.exists()), None)

if DATA_PATH is None:
    csv_files = list(Path(".").glob("*.csv"))
    if len(csv_files) == 1:
        DATA_PATH = csv_files[0]
    else:
        raise FileNotFoundError(
            "Could not find tracking_db(3).csv or tracking_db.csv. "
            "Put the CSV beside this notebook."
        )

df = pd.read_csv(DATA_PATH, low_memory=False)

print("Loaded:", DATA_PATH)
print("Rows:", len(df))
print("Columns:", len(df.columns))
print(df.head())

# 3. Parse dates
def parse_eta_ata(series, reference):
    day_first = pd.to_datetime(series, errors="coerce", dayfirst=True)
    month_first = pd.to_datetime(series, errors="coerce", dayfirst=False)
    ref = pd.to_datetime(reference, errors="coerce")

    result = day_first.copy()
    mask = ref.notna()

    result.loc[mask] = day_first.loc[mask].where(
        (day_first.loc[mask] - ref.loc[mask]).abs()
        <= (month_first.loc[mask] - ref.loc[mask]).abs(),
        month_first.loc[mask]
    )

    return result.fillna(day_first).fillna(month_first)

df["updated_dt"] = pd.to_datetime(
    df["updated"], errors="coerce", dayfirst=True
)
df["etdSchedule_dt"] = pd.to_datetime(
    df["etdSchedule"], errors="coerce", dayfirst=True
)
df["etd_dt"] = pd.to_datetime(
    df["etd"], errors="coerce", dayfirst=True
)
df["etaSchedule_dt"] = pd.to_datetime(
    df["etaSchedule"], errors="coerce", dayfirst=True
)
df["eta_dt"] = parse_eta_ata(df["eta"], df["updated_dt"])
df["ata_dt"] = parse_eta_ata(df["ata"], df["updated_dt"])

print("Date parsing completed.")

# 4. Create the target
df["arrival_delay_min"] = (
    df["ata_dt"] - df["etaSchedule_dt"]
).dt.total_seconds() / 60

df["congestion_risk"] = (
    df["arrival_delay_min"] > CONGESTION_THRESHOLD_MIN
).astype("int8")

print("Target definition:")
print(
    f"Congestion Risk = actual arrival > "
    f"{CONGESTION_THRESHOLD_MIN} minutes late"
)

valid = df["arrival_delay_min"].notna()

print("\nValid target rows:", int(valid.sum()))
print(
    df.loc[valid, "congestion_risk"]
      .value_counts()
      .sort_index()
      .rename(index={0: "Normal", 1: "Congestion Risk"})
      .to_frame("count")
)

# 5. Create ONE prediction record per voyage
# Use the latest tracking observation available BEFORE scheduled arrival.
# This prevents post-arrival information from entering the prediction.

work = df.dropna(subset=[
    "updated_dt",
    "etaSchedule_dt",
    "ata_dt",
    "imo",
    "depPort",
    "arrPort"
]).copy()

work["voyage_key"] = (
    work["imo"].astype(str)
    + "|" + work["depPort"].astype(str)
    + "|" + work["arrPort"].astype(str)
    + "|" + work["etaSchedule_dt"].dt.strftime("%Y-%m-%d %H:%M:%S")
)

pre_arrival = work[
    work["updated_dt"] <= work["etaSchedule_dt"]
].copy()

latest_idx = (
    pre_arrival
    .groupby("voyage_key")["updated_dt"]
    .idxmax()
)

snap = (
    pre_arrival.loc[latest_idx]
    .sort_values("updated_dt")
    .reset_index(drop=True)
)

print("Raw tracking rows:", len(df))
print("Unique voyages:", len(snap))
print("Rows removed as repeated tracking observations:",
      len(df) - len(snap))

# 6. Feature engineering
m = snap.copy()

m["eta_gap_min"] = (
    m["eta_dt"] - m["etaSchedule_dt"]
).dt.total_seconds() / 60

m["etd_gap_min"] = (
    m["etd_dt"] - m["etdSchedule_dt"]
).dt.total_seconds() / 60

m["lead_time_min"] = (
    m["etaSchedule_dt"] - m["updated_dt"]
).dt.total_seconds() / 60

for c in ["eta_gap_min", "etd_gap_min", "lead_time_min"]:
    m[c] = m[c].clip(-1000, 1000)

# Calendar
m["snapshot_hour"] = m["updated_dt"].dt.hour
m["snapshot_dow"] = m["updated_dt"].dt.dayofweek
m["snapshot_month"] = m["updated_dt"].dt.month

m["eta_hour"] = m["etaSchedule_dt"].dt.hour
m["eta_dow"] = m["etaSchedule_dt"].dt.dayofweek
m["eta_month"] = m["etaSchedule_dt"].dt.month

# Movement
for c in ["cog", "hdg"]:
    angle = np.deg2rad(pd.to_numeric(m[c], errors="coerce"))
    m[c + "_sin"] = np.sin(angle)
    m[c + "_cos"] = np.cos(angle)

m["heading_difference"] = np.abs(
    (
        pd.to_numeric(m["cog"], errors="coerce")
        - pd.to_numeric(m["hdg"], errors="coerce")
        + 180
    ) % 360 - 180
)

# Route
m["route"] = (
    m["depPort"].fillna("UNK").astype(str)
    + ">"
    + m["arrPort"].fillna("UNK").astype(str)
)

# Historical congestion rates.
# shift(1) means a voyage never uses its own target.
for group_col, feature_name in [
    ("route", "route_history_rate"),
    ("arrPort", "arrival_port_history_rate"),
    ("imo", "vessel_history_rate"),
    ("snapshot_hour", "hour_history_rate"),
    ("snapshot_dow", "weekday_history_rate")
]:
    m[feature_name] = m.groupby(group_col)["congestion_risk"].transform(
        lambda s: s.shift(1).expanding(min_periods=5).mean()
    )

FEATURES = [
    "lat", "long", "sog", "cog", "hdg",
    "heading_difference",
    "eta_gap_min", "etd_gap_min", "lead_time_min",
    "snapshot_hour", "snapshot_dow", "snapshot_month",
    "eta_hour", "eta_dow", "eta_month",
    "route", "depPort", "arrPort",
    "route_history_rate",
    "arrival_port_history_rate",
    "vessel_history_rate",
    "hour_history_rate",
    "weekday_history_rate"
]

X = m[FEATURES].replace([np.inf, -np.inf], np.nan)
y = m["congestion_risk"].astype(int)

print("Feature count:", len(FEATURES))

# 7. STRICT chronological split
# Nothing from the future is allowed to train the past.

n = len(m)

train_end = int(n * 0.70)
val_end = int(n * 0.85)

X_train = X.iloc[:train_end].copy()
y_train = y.iloc[:train_end].copy()

X_val = X.iloc[train_end:val_end].copy()
y_val = y.iloc[train_end:val_end].copy()

X_test = X.iloc[val_end:].copy()
y_test = y.iloc[val_end:].copy()

print("TRAIN:", X_train.shape)
print("VALIDATION:", X_val.shape)
print("TEST:", X_test.shape)

print("\nTarget distribution")
print("Train congestion:", round(y_train.mean()*100, 2), "%")
print("Validation congestion:", round(y_val.mean()*100, 2), "%")
print("Test congestion:", round(y_test.mean()*100, 2), "%")

# Test labels remain isolated from model selection.

# 8. Preprocessing
numeric_features = X_train.select_dtypes(
    include=["number", "bool"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["object", "category"]
).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median"))
            ]),
            numeric_features
        ),
        (
            "cat",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore"))
            ]),
            categorical_features
        )
    ]
)

print("Numeric features:", len(numeric_features))
print("Categorical features:", categorical_features)

# 9. XGBoost — congestion-sensitive but regularized
xgb_model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.025,
    max_depth=3,
    min_child_weight=10,
    subsample=0.80,
    colsample_bytree=0.80,
    reg_alpha=1.0,
    reg_lambda=10.0,
    gamma=0.20,

    # Give the minority congestion class more importance.
    scale_pos_weight=2.0,

    objective="binary:logistic",
    eval_metric="logloss",
    tree_method="hist",
    random_state=RANDOM_STATE,
    n_jobs=-1
)

xgb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", xgb_model)
])

xgb_pipeline.fit(X_train, y_train)

xgb_val_prob = xgb_pipeline.predict_proba(X_val)[:, 1]
xgb_test_prob = xgb_pipeline.predict_proba(X_test)[:, 1]

print("XGBoost trained.")

# 10. LightGBM — congestion-sensitive but regularized
lgbm_model = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.03,
    num_leaves=7,
    max_depth=3,
    min_child_samples=40,
    subsample=0.85,
    colsample_bytree=0.85,
    reg_alpha=0.5,
    reg_lambda=10.0,

    scale_pos_weight=2.0,

    objective="binary",
    random_state=RANDOM_STATE,
    n_jobs=-1,
    verbosity=-1
)

lgbm_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", lgbm_model)
])

lgbm_pipeline.fit(X_train, y_train)

lgbm_val_prob = lgbm_pipeline.predict_proba(X_val)[:, 1]
lgbm_test_prob = lgbm_pipeline.predict_proba(X_test)[:, 1]

print("LightGBM trained.")

# 11. Validation-only threshold search: maximize accuracy with recall >= 0.80
# Keep a strong congestion recall while prioritizing overall accuracy.
best = None
for threshold in np.arange(0.15, 0.51, 0.01):
    val_prob_tmp = 0.50*xgb_val_prob + 0.50*lgbm_val_prob
    pred = (val_prob_tmp >= threshold).astype(int)
    acc = accuracy_score(y_val,pred); rec=recall_score(y_val,pred,zero_division=0); prec=precision_score(y_val,pred,zero_division=0); f1=f1_score(y_val,pred,zero_division=0)
    if rec >= 0.80:
        key=(acc,f1,rec)
        if best is None or key>best[0]: best=(key,threshold,acc,prec,rec,f1)
if best is None: raise ValueError("No threshold reached required recall.")
_,BEST_THRESHOLD,va,vp,vr,vf1=best
BEST_XGB_WEIGHT=0.50; BEST_LGB_WEIGHT=0.50
val_prob=0.50*xgb_val_prob+0.50*lgbm_val_prob
test_prob=0.50*xgb_test_prob+0.50*lgbm_test_prob
print(f"Selected threshold: {BEST_THRESHOLD:.2f}")
print(f"Validation accuracy: {va:.4f}")
print(f"Validation congestion precision: {vp:.4f}")
print(f"Validation congestion recall: {vr:.4f}")

# 12. Finalize validation-selected operating point
validation_pred = (val_prob >= BEST_THRESHOLD).astype(int)
print(f"Production threshold: {BEST_THRESHOLD:.2f}")
print(f"Validation accuracy: {accuracy_score(y_val, validation_pred):.4f}")
print(f"Validation congestion recall: {recall_score(y_val, validation_pred, zero_division=0):.4f}")

# 13. FINAL TEST PREDICTION
# This is the first point where the untouched test set is evaluated.

test_pred = (test_prob >= BEST_THRESHOLD).astype(int)

tn, fp, fn, tp = confusion_matrix(
    y_test, test_pred
).ravel()

test_metrics = {
    "Accuracy": accuracy_score(y_test, test_pred),
    "Congestion Precision": precision_score(
        y_test, test_pred, zero_division=0
    ),
    "Congestion Recall": recall_score(
        y_test, test_pred, zero_division=0
    ),
    "Congestion F1": f1_score(
        y_test, test_pred, zero_division=0
    ),
    "Congestion F2": fbeta_score(
        y_test, test_pred, beta=2, zero_division=0
    ),
    "Balanced Accuracy": balanced_accuracy_score(
        y_test, test_pred
    ),
    "ROC-AUC": roc_auc_score(
        y_test, test_prob
    )
}

print("========== FINAL TEST RESULTS ==========")

for metric, value in test_metrics.items():
    print(f"{metric:25s}: {value:.4f} ({value*100:.2f}%)")

print("\n========== CONFUSION MATRIX ==========")
print(confusion_matrix(y_test, test_pred))

print("\nTN:", tn)
print("FP:", fp)
print("FN:", fn)
print("TP:", tp)

print("\n========== CLASSIFICATION REPORT ==========")
print(
    classification_report(
        y_test,
        test_pred,
        target_names=["Normal", "Congestion Risk"],
        digits=4,
        zero_division=0
    )
)

# 14. Final congestion-focused confusion matrix
cm = confusion_matrix(y_test, test_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Normal", "Congestion Risk"]
)

disp.plot(values_format="d")
plt.title(
    f"FINAL TEST — XGBoost + LightGBM\n"
    f"Threshold = {BEST_THRESHOLD:.2f}"
)
plt.tight_layout()
plt.close()

print(
    f"Congestion Recall = TP / (TP + FN) = "
    f"{tp} / ({tp} + {fn}) = "
    f"{tp/(tp+fn):.2%}"
)

# 15. Verify that the test set was not used for threshold selection
print("TEST SET AUDIT")
print("Test rows:", len(X_test))
print("Threshold source: VALIDATION ONLY")
print("Test labels used during model training: NO")
print("Test labels used during threshold selection: NO")
print("Test predictions generated only after model selection: YES")

# 16. Save the complete production artifacts
MODEL_DIR = Path("l1_congestion_production")
MODEL_DIR.mkdir(exist_ok=True)

# Save confusion matrix plot (directory now guaranteed to exist)
disp.plot(values_format="d")
plt.title(f"FINAL TEST — XGBoost + LightGBM\nThreshold = {BEST_THRESHOLD:.2f}")
plt.tight_layout()
plt.savefig(MODEL_DIR / "confusion_matrix.png", dpi=80)
plt.close()

joblib.dump(
    xgb_pipeline,
    MODEL_DIR / "xgboost_pipeline.joblib"
)

joblib.dump(
    lgbm_pipeline,
    MODEL_DIR / "lightgbm_pipeline.joblib"
)

metadata = {
    "project": "L1 Container Congestion Predictor",
    "target": "congestion_risk",
    "target_rule": f"ATA > etaSchedule + {CONGESTION_THRESHOLD_MIN} minutes",
    "ensemble": "50% XGBoost + 50% LightGBM",
    "threshold": BEST_THRESHOLD,
    "features": FEATURES,
    "metrics": test_metrics,
    "confusion_matrix": cm.tolist(),
    "test_split": "last 15% chronologically",
    "leakage_protection": True
}

joblib.dump(
    metadata,
    MODEL_DIR / "metadata.joblib"
)

print("Saved production artifacts to:")
print(MODEL_DIR.resolve())

"""# Interpretation for the L1 challenge

The ML model predicts:

> **Will this vessel be at congestion risk?**

The result can then be passed to the operational layer:

```text
Vessel tracking data
        ↓
XGBoost + LightGBM
        ↓
Congestion probability
        ↓
Normal / Congestion Risk
        ↓
Prioritise high-risk vessels
        ↓
Berth / crane optimisation
        ↓
72-hour port operations plan
```

### Critical limitation

The tracking dataset does not contain direct berth capacity, crane availability, yard occupancy, or container-volume information. Therefore this notebook should be presented as the **Congestion Risk Prediction ML module**, not as the complete berth/crane optimiser.

"""